---
title: "Wöchentliche Vorbereitung auf die Seminar-Sitzung"
author: "Felix Dietrich"
categories:
  - "BA Neue Medien / Online-Kommunikation KF/BF C"
  - "Sose 2024"
csl: "../bib/apa-cv.csl"
bibliography: "../bib/24-1-nmok.bib"
suppress-bibliography: true
link-citations: false
---

## Leseaufgabe

Um sich auf die nächste Sitzung vorzubereiten, **lesen Sie bitte das folgende Paper** (PDF im LMS):

@klimmtBiographicResonanceTheory2021

Machen Sie sich während der Lektüre **Notizen zu den folgenden Fragen**. Sie sollten in der Lage sein, diese **Fragen in der Sitzung zu beantworten** und **mit Ihren Kommiliton:innen darüber zu diskutieren**.

- Was ist die zentrale theoretische Lücke in bisherigen Konzepten, die von Klimmt und Rieger (2021) beschrieben wird, und wie schlagen die Autor:innen vor, diese zu schließen?
- Was sind Eigenschaften des Medieninhalts, die biographisches Resonanzerleben auslösen können?
- Wie lässt sich das Erleben biographischer Resonanz bei der Mediennutzung beschreiben und warum ist dies für Mediennutzer:innen bedeutsam?
- Wie lassen sich diese Erfahrungen vor dem Hintergrund des NEAR (Tamborini et al., 2021; siehe vorige Sitzung) beschreiben?
- Inwieweit passt diese theoretische Linse mit den persönlichen Erfahrungen, die wir in der vorigen Sitzung besprochen haben, überein?

## Besprechung in der Sitzung

### Was ist die zentrale theoretische Lücke in bisherigen Konzepten, die von Klimmt und Rieger (2021) beschrieben wird, und wie schlagen die Autor:innen vor, diese zu schließen?

- Zentrale Frage: Warum ist eine Rezeptionssituation für eine bestimmte Person bedeutsam ist: “What is missing in such current understanding of meaningful entertainment experiences is an approach to the user’s subjective, individual construction of meaning. “What is the meaning that appears to viewer X when watching movie Y? How is that meaningful to her/him?””
- Individuelle sinnkonstruktion der rezipient:in
- Fokus auf Mediennutzer:in, nicht nur auf den Medieninhalt (Interaktion)
- “Central to our proposition is that each member of the audience brings her or his personal biography to the process of entertainment consumption, and that meaningfulness will arise if some element of the chosen message resonates with some relevant part of a user’s personality, subjective history, and/or situation in life”
- “We build on these perspectives to conceptualize experiences of meaningfulness as outcome of media entertainment’s biographic resonance, that is, the emotionally loaded experience that a received entertainment content has something important to do with one’s self, one’s situation, one’s life history, and/or one’s (biographically rooted) current questions about life.”
- Im Hinblick auf die Suche nach und das Erleben von Sinnhaftigkeit durch den Einzelnen spielen kritische Lebensereignisse eine wichtige Rolle


### Was sind Eigenschaften des Medieninhalts, die biographisches Resonanzerleben auslösen können?

- Charaktere/Medienpersonae
  - Ähnlichkeit zu Rezipient:in; zB Charakterzüge, Haltungen/Einstellungen
  - Door opener, Entdecken von Ähnlichkeit ermöglicht elaborierte Verabeitung von Informationen
- Situationen
  - Themenübergreifende Beziehungen/Themen, z.B. Besprechung von Krisenthemen -> Allgemeingültige Resonanz (vgl. Fokus auf Inhalte bei Tamborini et al.)
  - "Because of the increased personal involvement, he or she will mobilize greater interest, more serious elaboration, and less readiness to remain in a “light-hearted,” escapistic stance toward the message"
- Entscheidungen
  - Inspiration durch die Entscheidung der Medienpersona
  - "Hence, under conditions of biographic resonance, entertainment portrayals of character decisions can serve as material for audience members’ personal meaning making [past decisions] (Park, 2010) and crisis decision-making [future decisions] (Sweeny, 2008)."
- Metaphern
  - Anwendung auf komplexe Sacheverhalte des eigenen Lebens
  - Reduktion von Komplexität
  - "they may show a user a new way of expressing or symbolizing a complex issue related to a life crisis, for instance, or illustrate a more optimistic perspective on how to frame and overcome a challenge in life"


### Wie lässt sich das Erleben biographischer Resonanz bei der Mediennutzung beschreiben und warum ist dies für Mediennutzer:innen bedeutsam?

- idR elaborierte Verarbeitung von Informationen, Nachdenken über bspw. die Situation, Entscheidung, Metapher, etc
- gemischter Affekt: negativer Affekt durch Erinnerung an negatives Erlebnis aus der eigenen Vergangenheit; Inspiration, wie man mit zukünftigen Krisen umgehen kann; Erinnerung an die Unterstützugn durch soziale Kontakte, Weiternetwicklung, Neudentdeckung, Selebstfindung (Hoffnung; Dankbarkeit)
- "This perceived connection between elements of the entertainment message and one’s own biography should make a profound difference for the user’s experience; because unlike escapist entertainment use and its typical focus on wishful identification, ideal selves and circumstances (e.g., superheroes, extraordinarily attractive people, places, and situations, cf. Katz & Foulkes, 1962), messages that trigger biographic resonance direct the user toward her or his real-life identity, her or his actual self and biographic circumstances."

**Bewältigung von Krisensituationen**

- Resonierende Medieninhalte helfen, eine Krisensituation zu verstehen
- Resonierende Medieninhalte helfen dabei, auf die äußeren Anforderungen einer Lebenskrise zu reagieren
- Resonierende Medieninhalte verdeutlichen die Bedeutung von Familie, Freunden und unterstützenden Personen in Lebenskrisen
- Resonierende Medieninhalte unterstützen die Affektregulierung und stimulieren Hoffnung
- Resonierende Medieninhalte fördern Veränderungen des Selbstkonzepts und ein Gefühl der Kompetenz
- Emotionale Folgen der biografischen Resonanz
  - negativer Affekt durch Erinnerung an die Lebenskrise
  - positiver Affekt durch selbsttranszendierende Emotionen wie Hoffnung und Dankbarkeit

