---
title: "Wöchentliche Vorbereitung auf die Seminar-Sitzung"
author: "Felix Dietrich"
categories:
  - "BA Neue Medien / Online-Kommunikation KF/BF C"
  - "Sose 2024"
csl: "../bib/apa-cv.csl"
bibliography: "../bib/24-1-nmok.bib"
suppress-bibliography: true
link-citations: false
---

## Leseaufgabe

Um sich auf die nächste Sitzung vorzubereiten, **lesen Sie bitte das folgende Paper** (PDF im LMS):

@vordererEntertainmentResonance2021

Machen Sie sich während der Lektüre **Notizen zu den folgenden Fragen**. Sie sollten in der Lage sein, diese **Fragen in der Sitzung zu beantworten** und **mit Ihren Kommiliton:innen darüber zu diskutieren**.

- Was sagt Vorderer (2021) darüber, inwieweit die Unterhaltungstheorie Bezug auf die soziale Welt, in die die Nutzer:innen von Unterhaltungsmedien eingebettet sind, nimmt? Wie könnte eine solche Einbettung mit Blick auf algorithmisch kuratierte Unterhaltungsplattformen aussehen?
- "Individuals are constantly tempted and affectively moving between what they want (e.g., fun) and who they want to be (e.g., an honest person)." Was ist damit gemeint, und wie können wir das mit den bisher dokumentierten Unterhaltungserfahrungen verknüpfen?
- Welche Rolle könnte algorithmische Kuratierung von Inhalten bei der von Vorderer (2021) diskutierten Unterscheidung zwischen "approach" und "avoidance" spielen?
- Fallen Ihnen Beispiele für Medienerfahrungen ein, die gemäß der Unterscheidung von Vorderer (2021) nicht als Unterhaltung zählen? (gerne bei der Einreichung der wöchentlichen Medienerfahrung berücksichtigen)
- "The problem with these resonant experiences, however, is that they are not available on demand." Welche Rolle könnte algorithmische Kuratierung von Inhalten hierbei spielen? 