---
title: "Wöchentliche Vorbereitung auf die Seminar-Sitzung"
author: "Felix Dietrich"
categories:
  - "BA Neue Medien / Online-Kommunikation KF/BF C"
  - "Sose 2024"
csl: "../bib/apa-cv.csl"
bibliography: "../bib/24-1-nmok.bib"
suppress-bibliography: true
link-citations: false
---

## Leseaufgabe

Um sich auf die nächste Sitzung vorzubereiten, **lesen Sie bitte das folgende Paper** (PDF im LMS):

@posslerThereEasyPath2023

Machen Sie sich während der Lektüre **Notizen zu den folgenden Fragen**. Sie sollten in der Lage sein, diese **Fragen in der Sitzung zu beantworten** und **mit Ihren Kommiliton:innen darüber zu diskutieren**.

- Was ist die zentrale Fragestellung, mit der sich der vorliegende Artikel beschäftigt? Überlegen Sie sich ein Beispiel für eine solche Nutzungserfahrung (im Kontext algorithmisch kuratierter Unterhaltungsplattformen)!
- Was sind die zentralen Annahmen und Mechanismen des *meaning-as-information* Frameworks?
- Wie lassen sich diese Annahmen auf die Mediennutzung übertragen?
- Inwiefern lassen sich die Befunde von Possler et al. (2023) mit der biographischen Resonanztheorie (Klimmt & Rieger, 2021) verknüpfen?
- Inwiefern unterscheidet sich das von Possler et al. (2023) beschriebene Phänomen von resonanten Medienerlebnissen (siehe Vorderer, 2021)?