---
title: "Wöchentliche Vorbereitung auf die Seminar-Sitzung"
author: "Felix Dietrich"
categories:
  - "BA Neue Medien / Online-Kommunikation KF/BF C"
  - "Sose 2024"
csl: "../bib/apa-cv.csl"
bibliography: "../bib/24-1-nmok.bib"
suppress-bibliography: true
link-citations: false
---

## Leseaufgabe

Um sich auf die nächste Sitzung vorzubereiten, **lesen Sie bitte eines der folgenden Paper** (PDF im LMS):

**Nachnamen A-H:**

@andersenArchivingOrderingSearching2018

**Nachnamen I-Z:**

@thorsonCuratedFlowsFramework2016

Machen Sie sich während der Lektüre **Notizen zu den folgenden Fragen**. Sie sollten in der Lage sein, diese **Fragen in der Sitzung zu beantworten** und **mit Ihren Kommiliton:innen darüber zu diskutieren**.

- Wie beeinflussen digitale Medienplattformen und Algorithmen die Art und Weise, wie Informationen kuratiert und den Nutzer:innen präsentiert werden?
- Auf welche Weise überschneiden sich die Konzepte der "tiefen Mediatisierung" und der "kuratierten Ströme" bei der Untersuchung der Auswirkungen der Medien auf die Gesellschaft?
- Welche Auswirkungen hat die algorithmusgesteuerte Kuratierung von Inhalten auf das individuelle Nutzerverhalten und die Kommunikationsmuster der Gesellschaft?
- Welche Rolle spielen die einzelnen Mediennutzer:innen und sozialen Kontakte bei der Kuratierung von Informationen, und wie wird dieser Prozess laut den beiden Artikeln durch digitale Plattformen vermittelt?
- Wo finden wir Anknüpfungspunkte zur Unterhaltungstheorie?