---
title: "Wöchentliche Vorbereitung auf die Seminar-Sitzung"
author: "Felix Dietrich"
categories:
  - "BA Neue Medien / Online-Kommunikation KF/BF C"
  - "Sose 2024"
csl: "../bib/apa-cv.csl"
bibliography: "../bib/24-1-nmok.bib"
suppress-bibliography: true
link-citations: false
---

## Leseaufgabe

Um sich auf die nächste Sitzung vorzubereiten, **lesen Sie bitte eines der folgenden Paper** (PDF im LMS):

**Nachnamen A-H:**

@bhandariWhyEveryoneTikTok2022

**Nachnamen I-Z:**

@leeAlgorithmicCrystalConceptualizing2022

Machen Sie sich während der Lektüre **Notizen zu den folgenden Leitfragen**. Sie sollten in der Lage sein, darüber **in der Sitzung mit Ihren Kommiliton:innen zu diskutieren**.

- Wie konzeptualisieren beide Artikel die Rolle von Algorithmen bei der Gestaltung von Nutzeridentitäten auf TikTok?
- Inwiefern beeinflusst die Wahrnehmung der Nutzer:innen mit Blick auf den TikTok-Algorithmus ihr Verhalten auf der Plattform?
- Was sind die Hauptunterschiede in der Beschreibung der Auswirkungen algorithmischer Kuratierung auf die Inhaltsvielfalt und das Benutzererlebnis in den beiden Artikeln?
  - Diskutieren Sie z.B. die Perspektive von Lee et al., dass der algorithmische Kristall das Gefühl der Zugehörigkeit fördert und kontrastieren Sie dies mit Bhandari und Bimos Befunden zur geringeren Relevanz sozialer Interaktionen zugunsten des Inhaltskonsums und den Implikationen für die Nutzerbeziehungen auf und außerhalb der Plattform.
- Welche methodischen Ansätze verwenden die Autor:innen, um die Beziehung zwischen TikTok-Algorithmen und Nutzeridentität zu untersuchen, und wie beeinflussen diese Ansätze ihre Ergebnisse?
