---
title: "Wöchentliche Vorbereitung auf die Seminar-Sitzung"
author: "Felix Dietrich"
categories:
  - "BA Neue Medien / Online-Kommunikation KF/BF C"
  - "Sose 2024"
csl: "../bib/apa-cv.csl"
bibliography: "../bib/24-1-nmok.bib"
suppress-bibliography: true
link-citations: false
---

## Leseaufgabe

Um sich auf die nächste Sitzung vorzubereiten, **lesen Sie bitte eines der folgenden Paper** (PDF im LMS):

**Nachnamen A-H:**

@strayWhatAreYou2021

**Nachnamen I-Z:**

@ziaraniSerendipityRecommenderSystems2021

Machen Sie sich während der Lektüre **Notizen zu den folgenden Leitfragen**. Sie sollten in der Lage sein, darüber **in der Sitzung mit Ihren Kommiliton:innen zu diskutieren**.

- Welche Hauptziele und Herausforderungen werden in beiden Artikeln bei der Verbesserung von Empfehlungssystemen identifiziert?
- Was ist mit dem Begriff der Serendipität gemeint?
- Inwiefern ist es notwendig, menschliche Werte und Kontextinformationen über die Nutzer:innen bei der Entwicklung von Empfehlungssystemen zu berücksichtigen?
- Welche Beispiele für die Anpassung von Empfehlungssystemen zur Förderung bestimmter Werte oder Ziele werden in beiden Artikeln diskutiert?
- Wie können wir unser erarbeitetes Wissen aus der Unterhaltungstheorie hier einfließen lassen?
