---
title: "Wöchentliche Vorbereitung auf die Seminar-Sitzung"
author: "Felix Dietrich"
categories:
  - "BA Neue Medien / Online-Kommunikation KF/BF C"
  - "Sose 2024"
csl: "../bib/apa-cv.csl"
bibliography: "../bib/24-1-nmok.bib"
suppress-bibliography: true
link-citations: false
---

## Leseaufgabe

Um sich auf die nächste Sitzung vorzubereiten, **lesen Sie bitte eines der folgenden Paper** (PDF im LMS):

**Nachnamen A-H:**

Dietrich, F., Arenz, A., & Reinecke, L. (2024). What Constitutes Experiences of Autonomy in Digital Technology Use? A (Computational) Scoping Review through the Lens of Self-Determination Theory. Manuscript under review.

**Nachnamen I-Z:**

@hutmacherPsychologyPersonalizationDigital2023

Machen Sie sich während der Lektüre **Notizen zu den folgenden Leitfragen**. Sie sollten in der Lage sein, darüber **in der Sitzung mit Ihren Kommiliton:innen zu diskutieren**.

"personalization in digital environments can ultimately have both positive and negative influences on the satisfaction of our basic needs for autonomy, competence, and relatedness." (Hutmacher & Appel, 2023, p. 29)

- Wie lassen sich diese paradoxen Zusammenhänge erklären?
- Welche Aspekte bennenen Hutmacher & Appel (2023) sowie Dietrich et al. (under review), die zu einer "Auflösung" dieses paradoxen Verhältnisses beitragen können?
- Wie können wir diese Überlegungen mit der Unterhaltungstheorie verknüpfen?
- Welche Auswirkungen kann hat dies auf das psychologische Wohlbefinden von Mediennutzer:innen?
- Überlegen Sie sich ein Mediennutzungsbeispiel, anhand dessen Sie die zuvor benannten Aspekte illustrieren können.

