---
title: "Abgabe 07"
author: "Felix Dietrich"
categories:
  - "BA Neue Medien / Online-Kommunikation KF/BF C"
  - "Sose 2024"
# csl: "../bib/apa.csl"
# bibliography: "../bib/24-1-nmok.bib"
# suppress-bibliography: true
# link-citations: false
---

## Einmalige schriftliche Abgabe

Um das Lernziel der Synthese (Themenblock: Unterhaltungserleben) zu erreichen und diese Fähigkeit für die Hausarbeit zu stärken, ist ein wissenschaftliches Essay Teil der Studienleistung. Auf Basis der Literatur und Diskussionen aus unseren Sitzungen verfassen Sie einen kurzen Aufsatz. In diesem dürfen Sie zitieren, aber auch frei Ideen und Kritikpunkte einbringen, die Sie sich überlegt oder im Kurs diskutiert haben. Die Essays können in Ihrer Form an den Diskussionsteil einer Hausarbeit angelehnt sein, aber auch eher theoretische oder praktische Inhalte diskutieren. Einige Leitfragen, die Sie bearbeiten können, finden Sie unten bzw. werden in den Sitzungen besprochen. Formale Hinweise:

-	600-800 Wörter (Wortzahl bitte unter dem Text festhalten)
-	Fließtextformatierung wie Hausarbeit (siehe [Informationen zur Hausarbeit](term_paper.html))
-	Abgabe via LMS
- Abgabefrist: 03.06.2024 um 23:59 Uhr

### Mögliche Leitfragen

- Warum sollte man sich mit Unterhaltungserfahrungen von Mediennutzer:innen in algorithmisch kuratierten Umgebungen aus wissenschatlicher Perspektive beschäftigen?
- Was macht Medieninhalte (in algorithmisch kuratierten Umgebungen) besonders unterhaltsam? Wo sind Grenzen der Unterhaltung?
- Wie können wir "Relatable Content" unterhaltungstheoretisch beschreiben?
- Wie könnte gute Forschung zu Unterhaltungserfahrungen in algorithmisch kuratierten Umgebungen aussehen? Was wären Hypothesen, die man empirisch untersuchen könnte/sollte?